Update threshold network
DefiLlama/defillama-server pull request #8791
Opened 2024-12-12 01:11 UTC by evandrosaturnino

## Description

Updates tBTC and it's parent protocol Threshold Network

[X] - [refactor: update tbtc protocol](https://github.com/DefiLlama/defillama-server/commit/c23c7bc1440deb244ec41aaea648e47e5bd46e6d)
[X] - [refactor: update threshold parent protocol](https://github.com/DefiLlama/defillama-server/commit/127686eaf2634f33a22b23970d83014bb712f25a)

- [x]  💅 Refactor (Non-breaking Change)
- [ ] 🐛 Bug fix (Non-breaking Change: Fixes an issue)
- [ ]  🛠️ Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..

## Notice

- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/evandrosaturnino/defillama-server/pulls) for the same update/change?

2024-12-17 15:22 UTC, 0xngmi requested changes

2024-12-17 15:22 UTC, 0xngmi commented on defi/src/protocols/data2.ts
> +    audits: "4",
2 just means that its audited, its not the number of audits

should leave as is

2024-12-17 15:22 UTC, 0xngmi commented on defi/src/protocols/data2.ts
> +    category: "Bridge",
why?

2025-01-07 01:23 UTC, evandrosaturnino commented on defi/src/protocols/data2.ts
> +    audits: "4",
Addressed in [fix: update tbtc audits value](https://github.com/DefiLlama/defillama-server/pull/8791/commits/0fc91c4515f8387edf49c67b16757e56756e177b)

2025-01-07 01:27 UTC, evandrosaturnino commented on defi/src/protocols/data2.ts
> +    category: "Bridge",
After internal discussion in Threshold, we ended up agreeing that Bridge category seems to be more precise when determining what tBTC protocol is. Mainly when comparing to other bridge protocol listed in this category (WBTC and others BTC-backed assets): https://defillama.com/protocols/bridge

2025-04-08 12:13 UTC, closed without merging